THIS_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

build:
	@make -C $(THIS_DIR)/cwrapper --no-print-directory
	@dotnet publish -r linux-x64 -c Release $(THIS_DIR)

run:
	@sudo LD_LIBRARY_PATH=$(THIS_DIR)/cwrapper $(THIS_DIR)/bin/Release/net6.0/linux-x64/publish/TinyNF $(TN_ARGS)

print-nf-name:
	@echo TinyNF
