APP := tinynf

CFLAGS += -O3 -march=native
# -gnatn turns on some inlining
CFLAGS += -gnatn
# remove unused stuff
CFLAGS += -cargs -ffunction-sections -fdata-sections -largs -Wl,--gc-sections

# Always clean, just in case
build:
	@gnatclean $(APP)
	@gnatmake $(APP) $(CFLAGS)

run:
	@sudo ./$(APP) $(TN_ARGS)

print-nf-name:
	@echo $(APP)

# The Ada driver doesn't try to have short timeouts (see ixgbe_device.adb)
init:
	@sleep 30
