APP := tinynf

CFLAGS += -O3 -g -march=native
# -gnatn turns on some inlining
CFLAGS += -gnatn
#CFLAGS += -fno-inline
# remove unused stuff
CFLAGS += -cargs -ffunction-sections -fdata-sections -largs -Wl,--gc-sections

# Always clean, just in case
build:
	@gnatclean $(APP)
	@gnatmake $(APP) $(CFLAGS)

run:
	@sudo ./$(APP) $(TN_ARGS)

print-nf-name:
	@echo $(APP)
