# Benchmarking-only makefile

# Current directory
TN_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# Include the normal one, for compilation
include $(TN_DIR)/Makefile

build: tn_default

# Preserve LD_LIBRARY_PATH so that util/perf.h can find libPAPI
run:
	@sudo LD_LIBRARY_PATH="$$LD_LIBRARY_PATH" ./tinynf $(TN_ARGS)

print-nf-name:
	@echo tinynf
