THIS_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# this --manifest-path trick is the equivalent to make -C, see https://github.com/rust-lang/cargo/issues/1485
build:
	@cargo build --manifest-path=$(THIS_DIR)/Cargo.toml --release

run:
	@sudo $(THIS_DIR)/target/release/tinynf $(TN_ARGS)

print-nf-name:
	@echo tinynf
