# Get this directory
THIS_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# Run the setup script, in case it hasn't been run yet
_IGNORED := $(shell $(THIS_DIR)/setup.sh 2>/dev/null)

TN_BATCH_SIZE ?= 1

build:
	@cd '$(THIS_DIR)/ixy'; cmake -D CMAKE_C_FLAGS='-DIXY_BATCH_SIZE=$(TN_BATCH_SIZE)' .; make clean; make

run:
	@sudo '$(THIS_DIR)/ixy/setup-hugetlbfs.sh'
	@sudo '$(THIS_DIR)/ixy/ixy-fwd' $(addprefix 0000:,$(TN_ARGS))

print-nf-name:
	@echo ixy-fwd
